### ISSUE TITLE
Let me know that the app is performing work while uploading audio and images

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#233]
If there is asynchronous work being performed, uploading, validating, saving, publishing - show me a “working…” indicator. Turning gear, spinner, something to show me that work and activity is happening.

**Comment by farski** [comment]
@chrisrhoden Tracking this manually seems onerous; is there a good way of tracking all these async ops, or will we have to invent something?

**Comment by chrisrhoden** [comment]
@farski It's pretty trivial to do this for anything that happens through ngHal, or even through `$http` in general. Uploads will require a little more work but we do have a good entrypoint to add this. I have a bunch of questions about how this is supposed to work, though, since the list @driki has provided here are things that are *technically* asynchronous, but some of them are *practically* synchronous, and generally speaking I'd prefer to consider each case individually.

**Comment by farski** [comment]
This is covered for audio and image uploads; is there anything else that needs an indicator, like feed creation? Is that one even reasonable to do?
