### ISSUE TITLE
Let me preview/hear my audio file(s) before I have published it

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#234]
After I have uploaded my audio file(s) I want to hear that it is the right one. I should be able to click the play button in my unpublished and unsaved story and hear it.

**Comment by farski** [comment]
The play button the story page preview? Or a button inside the edit modal? (If the former, how does it handle multiple files/versions?)

**Comment by driki** [comment]
I think we can accomplish this with the play button in the page preview. If there are multiple audio files we present them just as we do with any other segmented story, showing the markers.

To switch to a different version I suggest that we use the Preview function that appears in the top nav, which would allow the user to switch between the presentation of the versions. Preview - Podcast, PRX Marketplace, PMP...

**Comment by chrisrhoden** [comment]
@driki sort of hate to jump in here, but do we think that the version selector in the nav would work for the general case of version switching (so, replacing the version tabs in the form)? It would probably make some things better but it might bury versions more than you would like.

I don't have a strong opinion one way or the other, but I *do* think it would be a mistake to mirror the version list in both places, especially since many of the versions will never be displayed in the context of the website (soundcloud, PMP, podcast, etc). Makes it sort of a hard sell to me to put the alternate audio versions into the preview player. Really don't like the idea of having the preview be on the Podcast version while you're editing the Marketplace version and wondering why it's not updating.

**Comment by chrisrhoden** [comment]
to further clarify, I think of the information architecture we have as a series of concentric boxes.

The state of the nav essentially "owns" **all** of the content of the page, so if the nav relates to a specific version and not the story in general, it feels like it also owns the form, and therefore the form should be forced to show the version that the nav is related to.

**Comment by farski** [comment]
In read-only mode, will switching a version change only what is in the player, or can it update other parts of the page as well?

**Comment by driki** [comment]
@chrisrhoden yes, having these non-PRX outlets for versions or even the podcast version that is ours presents a challenge to figure out what a preview means given that we can't render out how it is going to look on the other services. So, then I guess we are back to having that audio preview at the version level inside of the editor (if we need it at all). I suggest that we don't offer playback for the audio inside of the Story Editor then, at lest yet. You can rearrange and change the order, but we don't need playback.

**Comment by driki** [comment]
While www.prx.org is serving both listeners and buyers it seems that it needs to not only update the audio, but also the other information. Titles and descriptions that are intended for those licensing should update to reflect the language that is used to market and sell to them vs. what is shown to the listeners.
